---

- name: Install PostgreSQL (Homebrew)
  homebrew:
    name:
      - postgresql
      - postgis
    state: present
  become: true
  become_user: "{{ postgresql_dev_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

- name: Check if PostgreSQL is started (Homebrew)
  shell: "{{ postgresql_dev_homebrew_bin | quote }} services list | grep '^postgresql ' | grep started"
  become: true
  become_user: "{{ postgresql_dev_homebrew_user }}"
  register: postgresql_dev_start_check_result
  changed_when: false
  failed_when: false
  when: ansible_pkg_mgr == 'homebrew'

- name: Start PostgreSQL (Homebrew)
  command: "{{ postgresql_dev_homebrew_bin | quote }} services start postgresql"
  become: true
  become_user: "{{ postgresql_dev_homebrew_user }}"
  register: postgresql_dev_start_result
  changed_when: postgresql_dev_start_result.rc != 0
  when: ansible_pkg_mgr == 'homebrew' and postgresql_dev_start_check_result.rc != 0

# Unsupported package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew is supported)"
  when: ansible_pkg_mgr != 'homebrew'
